### ISSUE TITLE
在Android 5.0上，貌似不怎么好使了

### ISSUE THREAD

**Issue by StormGens** [seven456/MultiChannelPackageTool#1]
按照作者的方法，同样一个包在经过处理后，在4.4版本上测试可以安装使用并读取到值，在5.0上安装包却解析失败。

**Comment by seven456** [comment]
android5.0在zip包校验上做了升级，我这个在近期稍微修改下就能解决这个问题；

**Comment by StormGens** [comment]
期待您的战果，5.0上好像对包的完整性也会检查文件大小是否和原来一致了。

**Comment by zourb** [comment]
期待支持 Android 5.0

**Comment by seven456** [comment]
已经修复Android5.0及以上系统不能安装打出的渠道包问题（校验apk文件的comment数据的长度）
