### ISSUE TITLE
contents googleplay;m360 中间应该是逗号吧

### ISSUE THREAD

**Issue by tianzhijiexian** [seven456/MultiChannelPackageTool#12]
contents googleplay;m360如果用这种分号我感觉是有问题的，不知道是不是我弄错了，希望指正
![image](https://cloud.githubusercontent.com/assets/9552155/15775915/3968bddc-29b7-11e6-9115-e900e5b497a9.png)
![image](https://cloud.githubusercontent.com/assets/9552155/15775931/520e6422-29b7-11e6-8881-bc54e87b93c5.png)

**Comment by KarnaughK** [comment]
是分号。。。只不过要加个斜杠。。。
渠道一/; 渠道二  
这样子。。。

**Comment by tianzhijiexian** [comment]
感谢！！！！
