### ISSUE TITLE
大神你好,请问可否在服务端实时完成流的传输,无需生成文件?

### ISSUE THREAD

**Issue by nametoa** [seven456/MultiChannelPackageTool#14]
现在我在做多应用的多渠道分包,现在需求要生成的包较多，如果每个都生成包,那么就会极大的占用服务器的硬盘内存.故可否实现在服务器端的实时动态生成文件流(原先apk流在尾续写渠道内容)传输给移动端
目前考虑实现存在以下问题:
1.大文件流如果读到缓存中,那么并发大服务器内存压力会巨大。
2.因为无法确定文件大小无法断点续传。
3.这样的思路可否有方案实现?
如有好的突破方向,请引导一下,谢谢！

**Comment by seven456** [comment]
1、一般apk生成渠道包后是需要保留文件在服务器端的，因为每个文件的md5都不一样，很多下载器会校验文件md5；
2、本打包工具使用的是RandomAccessFile，只操作文件末尾的32kb以内字节，不会占用大量内存；
3、本打包工具支持动态添加渠道号然后直接被下载，因为速度极快不需要等待；
