### ISSUE TITLE
似乎传到google play以后，zip的注释丢掉了

### ISSUE THREAD

**Issue by MichaelArchangel** [seven456/MultiChannelPackageTool#17]
目测是google加了一些自己的东西然后重新打包了...

**Comment by seven456** [comment]
尝试添加： v2SigningEnabled false
https://developer.android.com/about/versions/nougat/android-7.0.html#apk_signature_v2

**Comment by MichaelArchangel** [comment]
@seven456 添加了，似乎没效果

**Comment by seven456** [comment]
自己用Beyond Compare对比本地apk和google play下载的apk有哪些地方不一样，apk比较后再比较二进制；

**Comment by MichaelArchangel** [comment]
@seven456 之前想这么做来着。但是没找到从google play下载的apk在哪里。似乎play商店直接就解压了，没存。商店后台也没看到下载处理过的apk的地方
