### ISSUE TITLE
Android 7.0 应用不能安装

### ISSUE THREAD

**Issue by AlphaBoom** [seven456/MultiChannelPackageTool#18]
渠道包安装时显示应用包已损坏

**Comment by seven456** [comment]
Android 7.0 引入一项新的应用签名方案 APK Signature Scheme v2
在build.gradle中添加“v2SigningEnabled false”即可；
signingConfigs {
      release {
       ...
        v2SigningEnabled false
      }
    }

https://developer.android.com/about/versions/nougat/android-7.0.html#apk_signature_v2
