### ISSUE TITLE
1.1版本Windows下bat脚本运行提示jar中没有清单属性

### ISSUE THREAD

**Issue by zourb** [seven456/MultiChannelPackageTool#2]
***********************************
多渠道打包工具
!
功能
--------
1. 不对apk文件解包和签名即可完成渠道打包功能；
2. 读取apk中的渠道号：执行MCPTool-check.bat，Java代码中使用MCPTool.jar中的readCo
ntent(path, password)方法读取；

?
使用方法
--------
1. 将apk文件放到MCPTool目录下
2. 将apk文件拖拽到MCPTool.bat上
3. 执行完成后会在当前目录下生成各个渠道的apk文件
***********************************

.........MCPTool..........
MCPTool-1.1.jar中没有主清单属性

按任意键退出……

**Comment by seven456** [comment]
该问题是没有配置Main函数入口，已经解决；
