### ISSUE TITLE
Run Failed

### ISSUE THREAD

**Issue by zcd526889295** [seven456/MultiChannelPackageTool#3]
unable to access to jarfile MCPTool-1.1.jar

**Comment by seven456** [comment]
你运行的哪个文件？是bat？

**Comment by zcd526889295** [comment]
恩
McpTool.bat。
求具体步揍。
谢谢



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 11:11
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
你运行的哪个文件？是bat？

**Comment by zcd526889295** [comment]
如何解决？



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 11:11
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
你运行的哪个文件？是bat？

**Comment by seven456** [comment]
MCPTool.bat里面用到了：java -jar MCPTool-1.1.jar，你配置下java的环境变量，保证java命令能正常执行，或者java命令前面补全完整的java文件路径；

**Comment by zcd526889295** [comment]
JDK Android环境变量我都是有的啊，关键是点击MCPTool.bat,点击任意就退出了



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 13:29
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
MCPTool.bat里面用到了：java -jar MCPTool-1.1.jar，你配置下java的环境变量，保证java命令能正常执行，或者java命令前面补全完整的java文件路径；

**Comment by zcd526889295** [comment]
我有急用，拜托指导下



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 13:29
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
MCPTool.bat里面用到了：java -jar MCPTool-1.1.jar，你配置下java的环境变量，保证java命令能正常执行，或者java命令前面补全完整的java文件路径；

**Comment by seven456** [comment]
java环境变量的配置：http://jingyan.baidu.com/article/f96699bb8b38e0894e3c1bef.html

**Comment by zcd526889295** [comment]
哎 。说了 环境变量那些我都是有的。

**Comment by zcd526889295** [comment]
环境变量我会不知道？？说了 unable access jar.........



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 14:18
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
java环境变量的配置：http://jingyan.baidu.com/article/f96699bb8b38e0894e3c1bef.html

**Comment by seven456** [comment]
1、解压jar看看，能正常解压吗？
2、java -jar 运行别的jar试试；

**Comment by zcd526889295** [comment]
哎  用不起来



zhangcd@danqoo.com
 
From: seven456
Date: 2015-09-23 14:37
To: seven456/MultiChannelPackageTool
CC: zcd526889295
Subject: Re: [MultiChannelPackageTool] Run Failed (#3)
1、解压jar看看，能正常解压吗？
2、java -jar 运行别的jar试试；
