### ISSUE TITLE
引入android项目，貌似需要API>=19..

### ISSUE THREAD

**Issue by YuFong** [seven456/MultiChannelPackageTool#6]
![image](https://cloud.githubusercontent.com/assets/13096695/13866296/e61e539e-ecee-11e5-8fba-eeba96014b9a.png)

**Comment by seven456** [comment]
@YuFong 
已经将@since改成JDK1.7
zipFile.getComment是写入渠道号时用的，一般发生在服务器端，Android客户端只做读取操作；
同时，你在Android项目中引入jar即可，不要直接放源码，这不是个好习惯；

**Comment by YuFong** [comment]
确实写只在服务端进行，已移除了写入的相关方法。然后因为，是要把这个读取渠道号的功能集成到SDK里，所以要求直接引入源码... 0.0
